project:
  type: book
  output-dir: docs

book:
  title: "Computational Methods for human population genetics and ancient DNA"
  author: "Various enthusiasts at the MPI-EVA"
  date: "9/21/2023"
  chapters:
    - index.qmd
    - Quarto_intro.qmd
    - poseidon.qmd
    - fstats.qmd
    - authentiCT.qmd
    - eager.qmd
    - fst.qmd
    - pca_mds.qmd
    - pmrread.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

